module Scratch.B1 where

-- B1 (working unification): the nine path→iso characterisation PAIRS can be
-- generated by ONE recursor.  Key idea: produce the ▶-chain iso and its
-- path→iso characterisation TOGETHER, as a record (a "⊗-chain"), with three
-- generic combinators:
--   chain-refl : ⊗-chain refl                       (base id-iso)
--   chain-∷    : ⊗-chain p → ⊗-chain (ap (a ∷_) p)  (the cons step, uniform)
--   chain-sym  : ⊗-chain p → ⊗-chain (sym p)        (for the sym-based bases)
-- Every helper path in Multicategory.agda is built from refl/++-assoc by
-- ap (a ∷_) and sym, so each of the nine pairs becomes a 2-3-line recursion
-- (or, for the double inductions, LOSES a layer: chain-sym replaces the inner
-- recursion of assocₘ-flatten-iso / ic-slot₁-iso).  flat-from becomes refl.
-- The .⊗iso projections retain the definitional cons-reduction behaviour that
-- the downstream plug-assoc/plug-shift/plug-interchange displays rely on
-- (refl tests at the bottom).

open import Multicategory

open import 1Lab.Prelude hiding (id ; _∘_)
open import Cat.Base
import Cat.Reasoning as Cr
open import Cat.Monoidal.Base
open import Cat.Univalent using (path→iso)
open import Data.List
open import Data.List.Properties
import Multicategory.Instances.Monoidal as MIM

module _ {o h} (C : Precategory o h) (M : Monoidal-category C) where
  open Cr C
  open Monoidal-category M
  open MIM.Repr C M using (⊗-context ; path→iso-refl ; path→iso-ap-⊗)

  -- The iso induced by a context path (this is what all the laws transport by).
  ⊗-iso : {Γ Δ : List Ob} → Γ ≡ Δ → ⊗-context Γ ≅ ⊗-context Δ
  ⊗-iso p = path→iso (ap ⊗-context p)

  -- A ▶-chain iso together with the proof that ⊗-iso computes to it.
  -- (A record, not a Σ: the record's type constructor is matched by name, so
  -- the path index p is inferred at use sites; eta keeps .⊗iso reducing.)
  record ⊗-chain {Γ Δ : List Ob} (p : Γ ≡ Δ) : Type h where
    constructor chain
    field
      ⊗iso : ⊗-context Γ ≅ ⊗-context Δ
      char : ⊗-iso p ≡ ⊗iso

  open ⊗-chain

  chain-refl : {Γ : List Ob} → ⊗-chain (refl {x = Γ})
  chain-refl = chain id-iso path→iso-refl

  chain-∷ : (a : Ob) {Γ Δ : List Ob} {p : Γ ≡ Δ}
    → ⊗-chain p → ⊗-chain (ap (a ∷_) p)
  chain-∷ a {p = p} (chain i e) =
    chain (▶.F-map-iso i) (path→iso-ap-⊗ a (ap ⊗-context p) ∙ ap ▶.F-map-iso e)

  path→iso-sym : {A B : Ob} (p : A ≡ B) → path→iso (sym p) ≡ path→iso p Iso⁻¹
  path→iso-sym = J (λ _ p → path→iso (sym p) ≡ path→iso p Iso⁻¹)
    (path→iso-refl ∙ ≅-path refl ∙ sym (ap _Iso⁻¹ path→iso-refl))

  chain-sym : {Γ Δ : List Ob} {p : Γ ≡ Δ} → ⊗-chain p → ⊗-chain (sym p)
  chain-sym {p = p} (chain i e) =
    chain (i Iso⁻¹) (path→iso-sym (ap ⊗-context p) ∙ ap _Iso⁻¹ e)

  ----------------------------------------------------------------------
  -- The pairs, re-derived (three representatives + the shared ++-assoc base,
  -- covering: plain single induction, double induction, sym-at-base).
  ----------------------------------------------------------------------

  ++-assoc-chain : (Φ Ψ Ξ : List Ob) → ⊗-chain (++-assoc Φ Ψ Ξ)
  ++-assoc-chain []      Ψ Ξ = chain-refl
  ++-assoc-chain (a ∷ Φ) Ψ Ξ = chain-∷ a (++-assoc-chain Φ Ψ Ξ)

  -- was: slot-unbury-iso + slot-unbury-⊗ (11 lines)
  slot-unbury-chain : (Θ Φ : List Ob) (y : Ob) (Ψ Ξ : List Ob)
    → ⊗-chain (slot-unbury Θ Φ y Ψ Ξ)
  slot-unbury-chain []      Φ y Ψ Ξ = ++-assoc-chain Φ (y ∷ Ψ) Ξ
  slot-unbury-chain (a ∷ Θ) Φ y Ψ Ξ = chain-∷ a (slot-unbury-chain Θ Φ y Ψ Ξ)

  -- was: assocₘ-flatten-iso + assocₘ-flatten-⊗ (15 lines, DOUBLE induction);
  -- chain-sym absorbs the inner Ρ-recursion.
  assocₘ-flatten-chain : (Φ Ρ Ψ Ξ : List Ob) → ⊗-chain (assocₘ-flatten Φ Ρ Ψ Ξ)
  assocₘ-flatten-chain []      Ρ Ψ Ξ = chain-sym (++-assoc-chain Ρ Ψ Ξ)
  assocₘ-flatten-chain (a ∷ Φ) Ρ Ψ Ξ = chain-∷ a (assocₘ-flatten-chain Φ Ρ Ψ Ξ)

  -- was: ic-slot₁-iso + ic-slot₁-⊗ (13 lines, DOUBLE induction)
  ic-slot₁-chain : (Θ Γ Μ : List Ob) (y : Ob) (Κ : List Ob)
    → ⊗-chain (interchange-slot₁ Θ Γ Μ y Κ)
  ic-slot₁-chain []      Γ Μ y Κ = chain-sym (++-assoc-chain Γ Μ (y ∷ Κ))
  ic-slot₁-chain (a ∷ Θ) Γ Μ y Κ = chain-∷ a (ic-slot₁-chain Θ Γ Μ y Κ)

  -- was: assocₘ-boundary-iso + assocₘ-boundary-⊗ (11 lines)
  assocₘ-boundary-chain : (Θ Φ Ρ Ψ Ξ : List Ob) → ⊗-chain (assocₘ-boundary Θ Φ Ρ Ψ Ξ)
  assocₘ-boundary-chain []      Φ Ρ Ψ Ξ = assocₘ-flatten-chain Φ Ρ Ψ Ξ
  assocₘ-boundary-chain (a ∷ Θ) Φ Ρ Ψ Ξ = chain-∷ a (assocₘ-boundary-chain Θ Φ Ρ Ψ Ξ)

  ----------------------------------------------------------------------
  -- Compatibility with downstream uses.
  ----------------------------------------------------------------------

  -- (1) The characterisation the assembly needs is the .char projection:
  slot-unbury-⊗' : (Θ Φ : List Ob) (y : Ob) (Ψ Ξ : List Ob)
    → path→iso (ap ⊗-context (slot-unbury Θ Φ y Ψ Ξ))
    ≡ slot-unbury-chain Θ Φ y Ψ Ξ .⊗iso
  slot-unbury-⊗' Θ Φ y Ψ Ξ = slot-unbury-chain Θ Φ y Ψ Ξ .char

  -- (2) The cons-reduction the plug-assoc/plug-shift displays rely on is
  -- still definitional (refl):
  cons-red : (a : Ob) (Θ Φ : List Ob) (y : Ob) (Ψ Ξ : List Ob)
    → slot-unbury-chain (a ∷ Θ) Φ y Ψ Ξ .⊗iso .from
    ≡ (a ▶ slot-unbury-chain Θ Φ y Ψ Ξ .⊗iso .from)
  cons-red a Θ Φ y Ψ Ξ = refl

  -- (3) flat-from ((assocₘ-flatten-iso [] Ρ Ψ Ξ).from ≡ (++-assoc-⊗-iso Ρ Ψ Ξ).to,
  -- currently its own induction) becomes refl, because chain-sym's iso is Iso⁻¹:
  flat-from' : (Ρ Ψ Ξ : List Ob)
    → assocₘ-flatten-chain [] Ρ Ψ Ξ .⊗iso .from ≡ ++-assoc-chain Ρ Ψ Ξ .⊗iso .to
  flat-from' Ρ Ψ Ξ = refl
